### ISSUE TITLE
что-то не работают русские слова в кнопках

### ISSUE THREAD

**Issue by noremac09** [digital-stars/vk_api#1]
Привет. Спасибо огромное за класс для отправки кнопок. 

Пытаюсь вот отправить кнопку с русскими словами, и выходит вот такая каша.
![image](https://user-images.githubusercontent.com/25801549/41444124-a4e29062-7049-11e8-8ba5-2e39e89ef8b1.png)

Это на стороне ВК, или что-то с классом? Можешь глянуть?

**Comment by digitalstars** [comment]
Привет, да, такая проблема есть, поэтому для примера мы использовали английские слова. Пока не знаем в чем проблема, если сможешь ее решить, отпиши пожалуйста.

**Comment by digital-stars** [comment]
Привет, да, была небольшая проблема с классом, по фиксили, теперь кириллица отображается корректно !
